services:
  - type: web
    name: Senu-Md-pair
    build:
      command: npm install && npm run build
    start:
      command: pm2 start index.js --watch --deep-monitoring --attach --name Senu-Md
    port: 3000
    environment:
      NODE_ENV: production
    healthCheck:
      path: /health
      interval: 30000 # optional, defaults to 30000ms
      timeout: 5000 # optional, defaults to 5000ms
